/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ToinEmp;

import db_connect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import net.proteanit.sql.DbUtils;


public class empDesignation extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public empDesignation() {
        initComponents();
        
        con = dbconnect.connect();
        
            //load table
            tableload();
        
    }
    
    public void tableload(){
        
        try {
            String sql1 = "SELECT * FROM designation";
            pst = con.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    public int isnum(String aa){
       
          int a=1; 
        {
            for(int x=0;x<aa.length();x++)
            {
                if(!Character.isDigit(aa.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
   }
    
    public int checkamount(String amount){
     int a = 0;
    
        if(!amount.isEmpty())
        {
             
              
            for(int i=0;i<amount.length();i++)
            {
                if(Character.isLetter(amount.charAt(i)))
                {
                    
                    a=1;
                }
            }
        }
    
    return a;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        perbasaltxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        perottxt = new javax.swing.JTextField();
        tembasaltxt = new javax.swing.JTextField();
        pernopaytxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        temnopaytxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        temottxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(236, 151));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Designation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 58, 1020, 5));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Manager", "Supervisor", "Security Manager", "Order Manager", "Delivery Manager", "Maintainer", "Cashier", "Cheff", "Worker" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 179, -1));

        perbasaltxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perbasaltxtFocusLost(evt);
            }
        });
        jPanel1.add(perbasaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 179, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Basic Salary");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Basic Salary ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OT rate");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        perottxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                perottxtFocusLost(evt);
            }
        });
        jPanel1.add(perottxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 179, -1));

        tembasaltxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tembasaltxtFocusLost(evt);
            }
        });
        jPanel1.add(tembasaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 179, -1));

        pernopaytxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pernopaytxtFocusLost(evt);
            }
        });
        jPanel1.add(pernopaytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 179, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NoPay Rate");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("UPDATE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel10)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 140, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel9)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 140, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DELETE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 140, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CLEAR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(49, 49, 49))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 140, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cancel");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(47, 47, 47))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Designation", "Basic Salary(Permanant)", "Basic Salary(Temparary)", "OT Rate", "Leaves Level", "Nopay Rate", "Fual Allowance"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 1030, 160));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NoPay Rate");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, -1, -1));

        temnopaytxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                temnopaytxtFocusLost(evt);
            }
        });
        jPanel1.add(temnopaytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, 179, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OT rate");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, -1));

        temottxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                temottxtFocusLost(evt);
            }
        });
        jPanel1.add(temottxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 179, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 270, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Temporary");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Permenent");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 270, 10));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("(Perhour)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("(Perday)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("(Perday)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("(Perhour)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
       jPanel3.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
       jPanel3.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
       jPanel4.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
      jPanel5.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
       jPanel7.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        
        String desig = jComboBox1.getSelectedItem().toString();
        String persal = perbasaltxt.getText();
        String pernopay = pernopaytxt.getText();
        String perot = perottxt.getText();
        String temsal = tembasaltxt.getText();
        String temnopay = temnopaytxt.getText();
        String temot = temottxt.getText();
        
        if (desig.equals("Select") || persal.isEmpty() || pernopay.isEmpty() || perot.isEmpty() || temsal.isEmpty() || temnopay.isEmpty() || temot.isEmpty()){
        
        showMessageDialog(null,"Enter all essential data","Error", JOptionPane.ERROR_MESSAGE);
       
        //call is checkamount method
        }else if(checkamount(persal)==1){
        showMessageDialog(null,"Letters are not allowed for permanent salary.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(pernopay)==1){
        showMessageDialog(null,"Letters are not allowed for permanent nopay rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(perot)==1){
        showMessageDialog(null,"Letters are not allowed for permanent ot rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(temsal)==1){
        showMessageDialog(null,"Letters are not allowed for temporary salary.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(temnopay)==1){
        showMessageDialog(null,"Letters are not allowed for temporary nopay rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(temot)==1){
        showMessageDialog(null,"Letters are not allowed for temporary ot rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else{
       
        try {
            String desig_name = null;
            //db check for dublicates
            String sql ="SELECT * FROM designation  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            desig_name=rs.getString("desig_name");
                            
                            if(desig.equals(desig_name)){
                                showMessageDialog(null,"This Designation details already in the system!", "Error", JOptionPane.ERROR_MESSAGE);
                                jComboBox1.setSelectedIndex(0);
                                }
                            
                            }
            
            String d = "INSERT INTO designation (desig_name,persal,pernopay,perot,temsal,temnopay,temot) VALUES ('"+desig+"', '"+persal+"', '"+pernopay+"', '"+perot+"', '"+temsal+"', '"+temnopay+"', '"+temot+"')";
            pst = con.prepareStatement(d);
            pst.execute();

            //load table
            tableload();
            
            JOptionPane.showMessageDialog(null, "Succesfully added.");
            
        jComboBox1.setSelectedIndex(0);
        perbasaltxt.setText(null);
        pernopaytxt.setText(null);
        perottxt.setText(null);
        tembasaltxt.setText(null);
        temnopaytxt.setText(null);
        temottxt.setText(null);

        } catch (Exception e) {
            System.out.println(e);
        }
        }
        
           
        
           


        
        
        
        
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
       
        String desig = jComboBox1.getSelectedItem().toString();
        String persal = perbasaltxt.getText();
        String pernopay = pernopaytxt.getText();
        String perot = perottxt.getText();
        String temsal = tembasaltxt.getText();
        String temnopay = temnopaytxt.getText();
        String temot = temottxt.getText();
        
        if (desig.equals("Select") || persal.isEmpty() || pernopay.isEmpty() || perot.isEmpty() || temsal.isEmpty() || temnopay.isEmpty() || temot.isEmpty()){
        
        showMessageDialog(null,"Enter all essential data","Error", JOptionPane.ERROR_MESSAGE);
       
        //call is checkamount method
        }else if(checkamount(persal)==1){
        showMessageDialog(null,"Letters are not allowed for permanent salary.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(pernopay)==1){
        showMessageDialog(null,"Letters are not allowed for permanent nopay rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(perot)==1){
        showMessageDialog(null,"Letters are not allowed for permanent ot rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(temsal)==1){
        showMessageDialog(null,"Letters are not allowed for temporary salary.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(temnopay)==1){
        showMessageDialog(null,"Letters are not allowed for temporary nopay rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else if(checkamount(temot)==1){
        showMessageDialog(null,"Letters are not allowed for temporary ot rate.","Error", JOptionPane.ERROR_MESSAGE);
        }else{
         int x = JOptionPane.showConfirmDialog(null, "Do you want to update?");
         
         if(x==0){

        

            String sql = "UPDATE designation SET  persal = '"+persal+"', pernopay = '"+pernopay+"', perot = '"+perot+"', temsal = '"+temsal+"', temnopay = '"+temnopay+"', temot = '"+temot+"' WHERE desig_name = '"+desig+"'";
            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Succesfully updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }

            //load table
            tableload();
            
         } 
        }
        
  //           jComboBox1.setSelectedIndex(0);
//            jTextField1.setText(null);
//            jTextField2.setText(null);
//            jTextField3.setText(null);
//            jTextField4.setText(null);
//            jTextField5.setText(null);
        
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int r = jTable1.getSelectedRow();

        String desig = jTable1.getValueAt(r, 0).toString();
        String persal = jTable1.getValueAt(r, 1).toString();
        String pernopay = jTable1.getValueAt(r, 2).toString();
        String perot = jTable1.getValueAt(r, 3).toString();
        String temsal = jTable1.getValueAt(r, 4).toString();
        String temnopay = jTable1.getValueAt(r, 5).toString();
        String temot = jTable1.getValueAt(r, 6).toString();
        
        
        jComboBox1.setSelectedItem(desig);
        perbasaltxt.setText(persal);
        pernopaytxt.setText(pernopay);
        perottxt.setText(perot);
        tembasaltxt.setText(temsal);
        temnopaytxt.setText(temnopay);
        temottxt.setText(temot);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       
            jComboBox1.setSelectedIndex(0);
            perbasaltxt.setText(null);
            tembasaltxt.setText(null);
            perottxt.setText(null);
            pernopaytxt.setText(null);
            temnopaytxt.setText(null);
            temottxt.setText(null);
        
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
       
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this?");
        
        if(x==0){
            String desig = jComboBox1.getSelectedItem().toString();

            String sql = "DELETE FROM designation WHERE desig_name = '"+desig+"'";

            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Succesfully deleted.");
            } catch (Exception e) {
            }

            jComboBox1.setSelectedIndex(0);
            perbasaltxt.setText(null);
            tembasaltxt.setText(null);
            perottxt.setText(null);
            pernopaytxt.setText(null);
            temnopaytxt.setText(null);
            temottxt.setText(null);
        }

        //load table
        tableload();
        
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void perbasaltxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perbasaltxtFocusLost
      
        String persal = perbasaltxt.getText();
        if(!persal.isEmpty())
        {
              
            if(checkamount(persal)==1){
            
                JOptionPane.showMessageDialog(null, "Letters are not allowed.", "Error", JOptionPane.ERROR_MESSAGE);
            }  
            
        }
        
    }//GEN-LAST:event_perbasaltxtFocusLost

    private void pernopaytxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pernopaytxtFocusLost
       String amount = pernopaytxt.getText();
        if(!amount.isEmpty())
        {
              
              if(checkamount(amount)==1)
                {
                    
                    JOptionPane.showMessageDialog(null, "Letters are not allowed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        }
    }//GEN-LAST:event_pernopaytxtFocusLost

    private void perottxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_perottxtFocusLost
        String amount = perottxt.getText();
            if(!amount.isEmpty())
            {
              if(checkamount(amount)==1)
                {
                    
                    JOptionPane.showMessageDialog(null, "Letters are not allowed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        }
    }//GEN-LAST:event_perottxtFocusLost

    private void tembasaltxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tembasaltxtFocusLost
       String amount = tembasaltxt.getText();
        if(!amount.isEmpty())
        {
             if(checkamount(amount)==1)
                {
                    
                    JOptionPane.showMessageDialog(null, "Letters are not allowed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        }
    }//GEN-LAST:event_tembasaltxtFocusLost

    private void temnopaytxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temnopaytxtFocusLost
       String amount = temnopaytxt.getText();
        if(!amount.isEmpty())
        {
              if(checkamount(amount)==1)
                {
                    
                    JOptionPane.showMessageDialog(null, "Letters are not allowed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        }
    }//GEN-LAST:event_temnopaytxtFocusLost

    private void temottxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_temottxtFocusLost
       String amount = temottxt.getText();
        if(!amount.isEmpty())
        {
              if(checkamount(amount)==1)
                {
                    
                    JOptionPane.showMessageDialog(null, "Letters are not allowed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            
        }
    }//GEN-LAST:event_temottxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empDesignation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empDesignation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField perbasaltxt;
    private javax.swing.JTextField pernopaytxt;
    private javax.swing.JTextField perottxt;
    private javax.swing.JTextField tembasaltxt;
    private javax.swing.JTextField temnopaytxt;
    private javax.swing.JTextField temottxt;
    // End of variables declaration//GEN-END:variables
}
