package ToinEmp;


import db_connect.dbconnect;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Toin
 */
public class regEmp extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    String ImgPath = null;
    
    
    private String gender = null;
    private String state = null;
    
    public regEmp() {
        initComponents();
        
        //dbconnect
        con = dbconnect.connect();
    }
    
    public int isnum(String aa){
       
          int a=1; 
        {
            for(int x=0;x<aa.length();x++)
            {
                if(!Character.isDigit(aa.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
   }
    
    public int isletters(String aa){
       
          int a=1; 
        if(!aa.isEmpty())
        {
            for(int x=0;x<aa.length();x++)
            {
                if(!Character.isLetter(aa.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
   }
    
    public int checkemail(){
          int x=1;
            String Emaill = emailtxt.getText();
               String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
               if((!Emaill.matches(ePattern))&&(!Emaill.isEmpty())){
                   x=0;
               }
               return x;
      }
    
    public boolean checkage(){
        
        boolean status = false;
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        
        Date d1 = null;
        Date d2 = new Date();
        SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
        
        try {
            d1 = f.parse(f.format(dobtxt.getDate()));
            d2 = f.parse(f.format(d2));
        } catch (ParseException ex) {
            Logger.getLogger(regEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            double diff = d2.getTime()- d1.getTime();
        
        double hours = diff/(60*60*1000);
        
        double days = hours/24;
        
        int years = (int) (days/365);
        
        if(years<18){
            status=true;
        
        }
        
        return status;
          
    }
    
    public int checknic(String Nic){
    
        int a=1; 
        {
            for(int x=0;x<9;x++)
            {
                if(!Character.isDigit(Nic.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
    }
    
    public int checklicen(String aa){
       
          int a=1; 
        {
            for(int x=1;x<aa.length();x++)
            {
                if(!Character.isDigit(aa.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
   }
    
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
{
                ImageIcon myImage = null;

                if(imagePath != null)
            {
                myImage = new ImageIcon(imagePath);
            }
                else{
                        myImage = new ImageIcon(pic);
                    }

            Image img = myImage.getImage();
            Image img2 = img.getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(img2);
            return image;

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        ininametxt = new javax.swing.JTextField();
        nictxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dlicentxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        lphonetxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        qualitxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        addrstxt = new javax.swing.JTextArea();
        dobtxt = new com.toedter.calendar.JDateChooser();
        sdatetxt = new com.toedter.calendar.JDateChooser();
        passpanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(236, 151));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Add");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel20)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, -1, -1));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ADD");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel26)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name with initials");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIC no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, -1));

        fnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnametxtFocusLost(evt);
            }
        });
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        jPanel1.add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 270, -1));

        ininametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ininametxtFocusLost(evt);
            }
        });
        jPanel1.add(ininametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 270, 34));

        nictxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nictxtFocusLost(evt);
            }
        });
        jPanel1.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 270, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of birth");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Driving licence");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        dlicentxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dlicentxtFocusLost(evt);
            }
        });
        jPanel1.add(dlicentxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 270, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Land phone");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mobile");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Emails");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 270, -1));

        mobiletxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobiletxtFocusLost(evt);
            }
        });
        jPanel1.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 270, -1));

        lphonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lphonetxtFocusLost(evt);
            }
        });
        jPanel1.add(lphonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 270, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Civil state");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Single");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Married");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 129, -1, 390));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Designation");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Type");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Section");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Temporary", "Permanent" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 230, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5" }));
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox2FocusGained(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 230, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Start date");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(2263, 231, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Qualifications");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 129, -1, 390));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Employee Registration");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1060, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Photo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 260, 10));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("View Details");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(46, 46, 46))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 170, -1));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Cancel");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel28)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Start date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("UPDATE & DELETE");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(32, 32, 32))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 170, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Designation");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Manager", "Supervisor", "Security Manager", "Order Manager", "Delivery Manager", "Maintainer", "Cashier", "Cheff", "Worker", " " }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 230, -1));

        qualitxt.setColumns(20);
        qualitxt.setRows(5);
        jScrollPane1.setViewportView(qualitxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 250, 70));

        addrstxt.setColumns(20);
        addrstxt.setRows(5);
        jScrollPane2.setViewportView(addrstxt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 270, 50));
        jPanel1.add(dobtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 270, -1));
        jPanel1.add(sdatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 230, -1));

        passpanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Username");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Password");

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Re enter password");

        javax.swing.GroupLayout passpanelLayout = new javax.swing.GroupLayout(passpanel);
        passpanel.setLayout(passpanelLayout);
        passpanelLayout.setHorizontalGroup(
            passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGap(19, 19, 19)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jPasswordField1)
                    .addComponent(jPasswordField2))
                .addContainerGap())
        );
        passpanelLayout.setVerticalGroup(
            passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passpanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(passpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 380, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        jPanel8.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        jPanel8.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel9.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        jPanel10.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel10MouseExited

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
       view_emp view = new view_emp();
       view.setVisible(true);
       
      
       
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel11.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
       jPanel11.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
      this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        
        String fname = fnametxt.getText();
        String ininame = ininametxt.getText();
        String nic = nictxt.getText();
        String dlicen = dlicentxt.getText();
        String lphone = lphonetxt.getText();
        String mobile = mobiletxt.getText();
        String email = emailtxt.getText();
        String addrs = addrstxt.getText();
        String desig = jComboBox3.getSelectedItem().toString();
        String type = jComboBox1.getSelectedItem().toString();
        String section = jComboBox2.getSelectedItem().toString();
        String quali = qualitxt.getText();
        String usrName = jTextField1.getText();
        String passWrd = jPasswordField1.getText();
        String repassWrd = jPasswordField2.getText();
        int releave = 40;
        int renopay = 0;
        Date DOB = dobtxt.getDate();
        Date SDATE = sdatetxt.getDate();
        
//        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
//        
//        Date d1 = null;
//        Date d2 = new Date();
//        SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
        
        
//        try {
//            d1 = f.parse(f.format(dobtxt.getDate()));
//            d2 = f.parse(f.format(d2));
//        } catch (Exception e) {
//            System.out.println(e);
//        }
        
//        double diff = d2.getTime()- d1.getTime();
//        
//        double hours = diff/(60*60*1000);
//        
//        double days = hours/24;
//        
//        int years = (int) (days/365);
        
        if (buttonGroup1.getSelection()==null || buttonGroup2.getSelection()==null || fname.isEmpty() || ininame.isEmpty() || nic.isEmpty() || DOB==null || dlicen.isEmpty() || lphone.isEmpty() || mobile.isEmpty() || email.isEmpty() || addrs.isEmpty() || desig.isEmpty() || type.isEmpty() || section.isEmpty() || SDATE==null || quali.isEmpty()){
            showMessageDialog(null,"Enter all essential data", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
//        //nic validation
//        else if (!nic.isEmpty()){
//                  
//                   for(int x=0;x<9;x++)
//            {
//                if(!Character.isDigit(nic.charAt(x)))
//                {
//                    showMessageDialog(null,"First 9 characters should be numbers!");
//                       
//                 }   
//                }
//        
//        }
//        else if((nic.length()>10))
//               {
//                    showMessageDialog(null,"No more than 10 digits for NIC number");
//               }
//        else if((nic.length()<10))
//               {
//                    showMessageDialog(null,"Not enough digits for NIC number");
//                    
//                }
//        else if (nic.charAt(9)!='v' || nic.charAt(9)!='V')
//                {
//                   showMessageDialog(null,"Invalied NIC number"); 
//                }
//         
//                  //licen validation 
//        else if ((!Character.isLetter(dlicen.charAt(0))))
//                {
//                   showMessageDialog(null,"Invalied Licence no"); 
//                }
//          else if (!dlicen.isEmpty()){
//                  
//                   for(int x=1;x<dlicen.length();x++)
//            {
//                if(!Character.isDigit(dlicen.charAt(x)))
//                {
//                    showMessageDialog(null,"Letters are not allowed except first character!");
//                       
//                 }   
//                }
//        
//        }
//         else if((dlicen.length()>8))
//               {
//                    showMessageDialog(null,"No more than 8 digits for licence number");
//                    
//                }
//        else if((dlicen.length()<8))
//               {
//                    showMessageDialog(null,"Not enough digits for licence number");
//                    
//                }
//        
//        //land phone validation
//        else if(isnum(lphone)==0) //isnum method
//                {
//                    showMessageDialog(null,"Letters are not allowed in land phone Number");
//                }
//        else if((lphone.length()<10))
//                {
//                    showMessageDialog(null,"Not enough digits in land phone Number");
//                }
//        else if((lphone.length()>10))
//                {
//                    showMessageDialog(null,"Only 10 digits allowed in land phone Number");
//                }
//        
//        //mobile validation
//        else if(isnum(mobile)==0) //isnum method
//                {
//                    showMessageDialog(null,"Letters are not allowed in mobile phone Number", "Error", JOptionPane.ERROR_MESSAGE);
//                }
//        else if((mobile.length()<10))
//                {
//                    showMessageDialog(null,"Not enough digits in mobile phone Number","Error", JOptionPane.ERROR_MESSAGE);
//                }
//        else if((mobile.length()>10))
//                {
//                    showMessageDialog(null,"Only 10 digits allowed in mobile phone Number","Error", JOptionPane.ERROR_MESSAGE);
//                }
//        
//        //email validation
//              else if(checkemail()==0)//checkmail method
//                {
//                   showMessageDialog(null,"invalied email");
//               } 
//              
//              //age validate
//              else if(checkage(age)==1){
//                  showMessageDialog(null,"Not enough old for work in here!", "Error", JOptionPane.ERROR_MESSAGE);
//              
//              }else if(checkage(age)==2){
//                  showMessageDialog(null,"Too much old for work in here!", "Error", JOptionPane.ERROR_MESSAGE);
//              
//              }
//        
        else if(checkage()){
        
            showMessageDialog(null,"No suffient age to work here!","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else if(!passWrd.equals(repassWrd)){
        
            showMessageDialog(null,"Passwords aren't match!","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            
            SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String dob =dateformat.format(dobtxt.getDate());
            String sdate = dateformat.format(sdatetxt.getDate());
            
         
        
             
            
            
            try {
                
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        
                Date d1 = null;
                Date d2 = new Date();
                SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
                
                 d1 = f.parse(f.format(dobtxt.getDate()));
                 d2 = f.parse(f.format(d2));
                 
                    double diff = d2.getTime()- d1.getTime();
        
        double hours = diff/(60*60*1000);
        
        double days = hours/24;
        
        int years = (int) (days/365);
        
            InputStream img = new FileInputStream(new File(ImgPath));
            String d = "INSERT INTO employee (fname,ininame,nic,dob,licens,lphone,mobile,email,addrs,gender,state,age,desig,type,sec,sdate,quali,releave,renopay,img,usrname,passwrd) VALUES ('"+fname+"', '"+ininame+"', '"+nic+"', '"+dob+"', '"+dlicen+"', '"+lphone+"', '"+mobile+"', '"+email+"', '"+addrs+"' , '"+gender+"' , '"+state+"', '"+years+"', '"+desig+"', '"+type+"', '"+section+"', '"+sdate+"', '"+quali+"', '"+releave+"', '"+renopay+"', '"+img+"', '"+usrName+"', '"+repassWrd+"')";
            pst = con.prepareStatement(d);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully added.","Success", JOptionPane.INFORMATION_MESSAGE);
            
        fnametxt.setText(null);
        ininametxt.setText(null);
        nictxt.setText(null);
        dobtxt.setDate(null);
        dlicentxt.setText(null);
        lphonetxt.setText(null);
        mobiletxt.setText(null);
        emailtxt.setText(null);
        addrstxt.setText(null);
        jComboBox3.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        sdatetxt.setDate(null);
        qualitxt.setText(null);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
            }catch(Exception e){
                showMessageDialog(null,e,"Error", JOptionPane.ERROR_MESSAGE);
            }
        
        
        }
    
        
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        gender = "Male";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        gender = "Female";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        state = "Single";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        state = "Married";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
       up_del_Emp ude = new up_del_Emp();
       ude.setVisible(true);
        
        
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jComboBox2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusGained
        
          jComboBox2.removeAllItems();
        //set values to section combobox from db
       try {
 
            String sql ="SELECT DISTINCT sec_name FROM section "; 
            pst = con.prepareStatement(sql);
           
            rs =pst.executeQuery();
            
             while(rs.next()){
                 
                 String sec=rs.getString("sec_name");
                 jComboBox2.addItem(sec);
             }
             
    
       }
       catch(Exception e)
       {
           showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
       }
        
        
    }//GEN-LAST:event_jComboBox2FocusGained

    private void nictxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nictxtFocusLost
      String nic = nictxt.getText();
        
        if (!nic.isEmpty()){
                  
                
            if((nic.length()<10))
               {
                    showMessageDialog(null,"Not enough digits for NIC number", "Error", JOptionPane.ERROR_MESSAGE);
                    nictxt.setText(null);
                    
                }
                  
            else if((nic.length()>10))
               {
                    showMessageDialog(null,"No more than 10 digits for NIC number", "Error", JOptionPane.ERROR_MESSAGE);
                    nictxt.setText(null);
               }
                    else if(checknic(nic) == 0)//call checknic method
                    {
                    showMessageDialog(null,"First 9 characters should be numbers!", "Error", JOptionPane.ERROR_MESSAGE);
                    nictxt.setText(null);
                    
            }
        
            else if (nic.charAt(9)!='v' && nic.charAt(9)!='V')
                {
                   showMessageDialog(null,"Invalied NIC number", "Error", JOptionPane.ERROR_MESSAGE); 
                }
                
        
            else if(nic.length()==10){
                String nid=null;
        
         try {
           
                        String sql ="SELECT * FROM employee  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            nid=rs.getString("nic");
                            
                            if(nic.equals(nid)){
                                showMessageDialog(null,"This NIC number is already in database!", "Error", JOptionPane.ERROR_MESSAGE);
                                nictxt.setText(null);}
                            }
                        }
                    catch(Exception e)
                    {
                        showMessageDialog(null, e , "Error" , JOptionPane.ERROR_MESSAGE);
                    } 
        
       }
        }

        
    }//GEN-LAST:event_nictxtFocusLost

    private void dlicentxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dlicentxtFocusLost
        String dlicen = dlicentxt.getText();
        
        if(!dlicen.isEmpty()){
        if ((!Character.isLetter(dlicen.charAt(0))))
                {
                   showMessageDialog(null,"Invalied Licence no", "Error", JOptionPane.ERROR_MESSAGE); 
                   dlicentxt.setText(null);
                }
        else if (checklicen(dlicen)==0)//call checklicen method
          {
                 
                    showMessageDialog(null,"Letters are not allowed except first character!", "Error", JOptionPane.ERROR_MESSAGE);
                    dlicentxt.setText(null);
                      
        }
        else if((dlicen.length()<8))
               {
                    showMessageDialog(null,"Not enough digits for licence number", "Error", JOptionPane.ERROR_MESSAGE);
                    dlicentxt.setText(null);
                    
                }
          
         else if((dlicen.length()>8))
               {
                    showMessageDialog(null,"No more than 8 digits for licence number", "Error", JOptionPane.ERROR_MESSAGE);
                    dlicentxt.setText(null);
                    
                }
        
        }
    }//GEN-LAST:event_dlicentxtFocusLost

    private void fnametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnametxtFocusLost
       String name=fnametxt.getText();
        if(!name.isEmpty())
        {
            
            for(int x=0;x<name.length();x++)
            {   
                 if(name.charAt(x)==' ')
                {
                }
                 
               else if(!Character.isLetter(name.charAt(x)))
                {
                    showMessageDialog(null,"Only Letters are allowed", "Error", JOptionPane.ERROR_MESSAGE);
                   fnametxt.setText(null);
                    break;
                }
               
            }
            

        }
    }//GEN-LAST:event_fnametxtFocusLost

    private void ininametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ininametxtFocusLost
        String name=ininametxt.getText();
        if(!name.isEmpty())
        {
            
            for(int x=0;x<name.length();x++)
            {   
                 if(name.charAt(x)==' ')
                {
                }
                 
               else if(!Character.isLetter(name.charAt(x)))
                {
                    showMessageDialog(null,"Only Letters are allowed", "Error", JOptionPane.ERROR_MESSAGE);
                   ininametxt.setText(null);
                    break;
                }
               
            }
            

        }
    }//GEN-LAST:event_ininametxtFocusLost

    private void lphonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lphonetxtFocusLost
       
        String lphone = lphonetxt.getText();
        
        if(!lphone.isEmpty()){
        if(isnum(lphone)==0) //isnum method
                {
                    showMessageDialog(null,"Letters are not allowed in land phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    lphonetxt.setText(null);
                }
        else if((lphone.length()<10))
                {
                    showMessageDialog(null,"Not enough digits in land phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    lphonetxt.setText(null);
                }
        else if((lphone.length()>10))
                {
                    showMessageDialog(null,"Only 10 digits allowed in land phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    lphonetxt.setText(null);
                }
        }
    }//GEN-LAST:event_lphonetxtFocusLost

    private void mobiletxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobiletxtFocusLost
       
       String mobile = mobiletxt.getText();
       
       if(!mobile.isEmpty()){ 
       if(isnum(mobile)==0) //isnum method
                {
                    showMessageDialog(null,"Letters are not allowed in mobile phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    mobiletxt.setText(null);
                }
        else if((mobile.length()<10))
                {
                    showMessageDialog(null,"Not enough digits in mobile phone Number","Error", JOptionPane.ERROR_MESSAGE);
                    mobiletxt.setText(null);
                }
        else if((mobile.length()>10))
                {
                    showMessageDialog(null,"Only 10 digits allowed in mobile phone Number","Error", JOptionPane.ERROR_MESSAGE);
                    mobiletxt.setText(null);
                }
       }
    }//GEN-LAST:event_mobiletxtFocusLost

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost
        String email = emailtxt.getText();
        if(!email.isEmpty()){
        
        if(checkemail()==0)//checkmail method
                {
                   showMessageDialog(null,"Invalied email", "Error", JOptionPane.ERROR_MESSAGE);
                   emailtxt.setText(null);
              } 
        }
    }//GEN-LAST:event_emailtxtFocusLost

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_img.setIcon(ResizeImage(path, null));
            ImgPath = path;
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
       String Passpanel = jComboBox3.getSelectedItem().toString();
        
        if(Passpanel == "Worker"){
        passpanel.setVisible(false);
        }
        else{
        passpanel.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
       String usr = jTextField1.getText();
        
        if (!usr.isEmpty()){
                  
                try {
           
                        String sql ="SELECT * FROM employee  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            String Usrname=rs.getString("usrname");
                            
                            if(usr.equals(Usrname)){
                                showMessageDialog(null,"This username already in use. Please enter different username!", "Error", JOptionPane.ERROR_MESSAGE);
                                jTextField1.setText(null);}
                            }
                        }
                    catch(Exception e)
                    {
                        showMessageDialog(null, e , "Error" , JOptionPane.ERROR_MESSAGE);
                    } 
        
       }
        
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
       String pass = jPasswordField1.getText();
        
        if (!pass.isEmpty()){
                  
                try {
           
                        String sql ="SELECT * FROM employee  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            String Passwrd=rs.getString("passwrd");
                            
                            if(pass.equals(Passwrd)){
                                showMessageDialog(null,"Password in use!", "Error", JOptionPane.ERROR_MESSAGE);
                                jPasswordField1.setText(null);}
                            }
                        }
                    catch(Exception e)
                    {
                        showMessageDialog(null, e , "Error" , JOptionPane.ERROR_MESSAGE);
                    } 
        
       }
    }//GEN-LAST:event_jPasswordField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addrstxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField dlicentxt;
    private com.toedter.calendar.JDateChooser dobtxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField ininametxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField lphonetxt;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nictxt;
    private javax.swing.JPanel passpanel;
    private javax.swing.JTextArea qualitxt;
    private com.toedter.calendar.JDateChooser sdatetxt;
    // End of variables declaration//GEN-END:variables
}
