package ToinEmp;

import db_connect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Toin
 */
public class up_del_Emp extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    private String gender = null;
    private String state = null;
    
    
    public up_del_Emp() {
        initComponents();
        
        //dbconnect 
        con = dbconnect.connect();
        
        //load table
        tableload();
    }
    
    public void tableload()
    {
       try {
 
            String sql ="SELECT eid as EmpID,fname as Name FROM employee "; 
            pst = con.prepareStatement(sql);
           
            rs =pst.executeQuery();
            
              jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
             
    
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, "Error loading table", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }
    
    public int checknic(String Nic){
    
        int a=1; 
        {
            for(int x=0;x<9;x++)
            {
                if(!Character.isDigit(Nic.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
    }
    
    public int checklicen(String aa){
       
          int a=1; 
        {
            for(int x=1;x<aa.length();x++)
            {
                if(!Character.isDigit(aa.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
   }
    
    public int isnum(String aa){
       
          int a=1; 
        {
            for(int x=0;x<aa.length();x++)
            {
                if(!Character.isDigit(aa.charAt(x)))
                {
                    
                    a=0;
                }
            }

        } 
       return a;
   }
    
    public int checkemail(){
          int x=1;
            String Emaill = emailtxt.getText();
               String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
               if((!Emaill.matches(ePattern))&&(!Emaill.isEmpty())){
                   x=0;
               }
               return x;
      }
    
     public int checkage(String aage){
            int x=0;
            int ageint = Integer.parseInt(aage);
            
            if(ageint<18){
                x=1;
            }else if(ageint>=55){
                x=2;
            }
          return x;
    }
     
     public boolean checkage(){
        
        boolean status = false;
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        
        Date d1 = null;
        Date d2 = new Date();
        SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
        
        try {
            d1 = f.parse(f.format(dobtxt.getDate()));
            d2 = f.parse(f.format(d2));
        } catch (ParseException ex) {
            Logger.getLogger(regEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            double diff = d2.getTime()- d1.getTime();
        
        double hours = diff/(60*60*1000);
        
        double days = hours/24;
        
        int years = (int) (days/365);
        
        if(years<18){
            status=true;
        
        }
        
        return status;
          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        ininametxt = new javax.swing.JTextField();
        nictxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lphonetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        dlicentxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        dobtxt = new com.toedter.calendar.JDateChooser();
        sdatetxt = new com.toedter.calendar.JDateChooser();
        agetxt = new javax.swing.JLabel();
        passpanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(236, 151));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1125, 600));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1127, 600));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1125, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name with initials");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NIC no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        fnametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnametxtFocusLost(evt);
            }
        });
        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        jPanel1.add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 270, -1));

        ininametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ininametxtFocusLost(evt);
            }
        });
        jPanel1.add(ininametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 270, -1));

        nictxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nictxtFocusLost(evt);
            }
        });
        jPanel1.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 270, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of birth");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Driving licence");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        lphonetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lphonetxtFocusLost(evt);
            }
        });
        jPanel1.add(lphonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 270, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Land phone");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mobile");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Emails");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 270, -1));

        dlicentxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dlicentxtFocusLost(evt);
            }
        });
        jPanel1.add(dlicentxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 270, -1));

        mobiletxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobiletxtFocusLost(evt);
            }
        });
        jPanel1.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 270, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Civil state");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Age");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, -1, -1));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Single");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 640, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, -1, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Married");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 95, 10, 640));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Employee Registration");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 36, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 69, 999, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 390, 320));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search by Name / EID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 390, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 87, 11, 650));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Cancel");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel30)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 910, 210, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 60, -1));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel12MouseExited(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Update");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel31)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 210, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 270, 50));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EID");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 270, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Designation");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 230, 10));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Temporary", "Permanent" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 170, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Type");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Section");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3" }));
        jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox2FocusGained(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 170, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Start date");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Qualifications");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 170, 90));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Photo");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Change");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel22)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 180, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Manager", "Supervisor", "Security Manager", "Order Manager", "Delivery Manager", "Maintainer", "Cashier", "Cheff", "Worker" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 170, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Designation");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Delete");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel32)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 910, -1, 30));
        jPanel1.add(dobtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 270, -1));
        jPanel1.add(sdatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 170, -1));

        agetxt.setForeground(new java.awt.Color(255, 255, 255));
        agetxt.setText(":-");
        jPanel1.add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 700, 60, 20));

        passpanel.setBackground(new java.awt.Color(51, 51, 51));
        passpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Username");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Password");

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Re enter password");

        javax.swing.GroupLayout passpanelLayout = new javax.swing.GroupLayout(passpanel);
        passpanel.setLayout(passpanelLayout);
        passpanelLayout.setHorizontalGroup(
            passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(19, 19, 19)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jPasswordField1)
                    .addComponent(jPasswordField2))
                .addContainerGap())
        );
        passpanelLayout.setVerticalGroup(
            passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passpanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(passpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(passpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 740, 360, 160));

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
       this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel11.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel11.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        int x = JOptionPane.showConfirmDialog(null, "Do you want to update?");
        
        if(x==0){
        String eid = jLabel15.getText();
        String fname = fnametxt.getText();
        String ininame = ininametxt.getText();
        String nic = nictxt.getText();
        String dlicen = dlicentxt.getText();
        String lphone = lphonetxt.getText();
        String mobile = mobiletxt.getText();
        String email = emailtxt.getText();
        String addrs = jTextArea1.getText();
        String age = agetxt.getText();
        String desig = jComboBox3.getSelectedItem().toString();
        String type = jComboBox1.getSelectedItem().toString();
        String section = jComboBox2.getSelectedItem().toString();
        String quali = jTextArea2.getText();
        String gender = "";
        String state = "";
        String usrName = jTextField2.getText();
        String passWrd = jPasswordField1.getText();
        String repassWrd = jPasswordField2.getText();
        Date DOB = dobtxt.getDate();
        Date SDATE = sdatetxt.getDate();
        
       
        
        if(buttonGroup1.getSelection()==null || buttonGroup2.getSelection()==null || fname.isEmpty() || ininame.isEmpty() || nic.isEmpty() || DOB == null || dlicen.isEmpty() || lphone.isEmpty() || mobile.isEmpty() || email.isEmpty() || addrs.isEmpty() || desig.isEmpty() || type.isEmpty() || section.isEmpty() || SDATE == null || quali.isEmpty()){
            
            showMessageDialog(null,"Enter all essential data", "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
        else if(checkage()){
        
             showMessageDialog(null,"No suffient age to work here!","Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else if(!passWrd.equals(repassWrd)){
        
            showMessageDialog(null,"Passwords aren't match!","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        if(jRadioButton1.isSelected()){
            gender = "Male";
        }else if(jRadioButton2.isSelected()){
            gender = "Female";
        }
        
        if(jRadioButton3.isSelected()){
            state = "Single";
        }else if (jRadioButton4.isSelected()){
            state = "Married";
        }
        
        
        
            try {
                
                SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
                String dob =dateformat.format(dobtxt.getDate());
                String sdate = dateformat.format(sdatetxt.getDate());
                
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
////////////////////////////////////        
                 Date d1 = null;
                Date d2 = new Date();
                SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
                
                d1 = f.parse(f.format(dobtxt.getDate()));
                d2 = f.parse(f.format(d2));
                
                double diff = d2.getTime()- d1.getTime();
        
                double hours = diff/(60*60*1000);
        
                double days = hours/24;
        
                int years = (int) (days/365);
                
                String sql = "UPDATE employee SET fname = '"+fname+"', ininame = '"+ininame+"', nic = '"+nic+"', dob = '"+dob+"', licens = '"+dlicen+"', lphone = '"+lphone+"', mobile = '"+mobile+"', email = '"+email+"', addrs = '"+addrs+"', gender = '"+gender+"', state = '"+state+"', age = '"+age+"', desig = '"+desig+"', type = '"+type+"', sec = '"+section+"', sdate = '"+sdate+"', quali = '"+quali+"', usrname = '"+usrName+"', passwrd = '"+repassWrd+"' WHERE eid = '"+eid+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Succesfully updated.");
                
            } catch (Exception e) {
                showMessageDialog(null,e,"Error", JOptionPane.ERROR_MESSAGE);
            }
            
            //load table
            tableload();
            
        }
        }
        
        
        
        
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseEntered
         jPanel12.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel12MouseEntered

    private void jPanel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseExited
        jPanel12.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel12MouseExited

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String name1=jTextField1.getText();
         try {
 
            String sql ="SELECT eid,fname FROM employee where fname LIKE'%"+name1+"%' OR eid LIKE '%"+name1+"%' "; 
            pst = con.prepareStatement(sql);
           
            rs =pst.executeQuery();
            
              jTable1.setModel(DbUtils.resultSetToTableModel(rs));

             
       }
       catch(Exception e)
       {
          JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int r= jTable1.getSelectedRow( );
      
      String empid = jTable1.getValueAt(r, 0).toString();
      jLabel15.setText(empid);
      
      
        String fname;
        String ininame;
        String nic;
        String dob;
        String addrs;
        String licen;
        String email;
        String lphone;
        String mobile;
        String gender;
        String state;
        String age;
        String desig;
        String type;
        String sec;
        String sdate;
        String quali;
        String usrName;
        String passWrd;
        String repassWrd;
        
        
        
            try {
            String q="select * from employee where eid='"+empid+"'";
            pst=con.prepareStatement(q);
            rs=pst.executeQuery();
            if(rs.next())
            {
                rs=pst.executeQuery();
                while(rs.next()){
                    fname=rs.getString("fname");
                    ininame=rs.getString("ininame");
                    nic=rs.getString("nic");
                    dob=rs.getString("dob");
                    licen=rs.getString("licens");
                    lphone=rs.getString("lphone");
                    mobile=rs.getString("mobile");
                    email=rs.getString("email");
                    addrs=rs.getString("addrs");
                    gender=rs.getString("gender");
                    state=rs.getString("state");
                    age=rs.getString("age");
                    desig=rs.getString("desig");
                    type=rs.getString("type");
                    sec=rs.getString("sec");
                    sdate=rs.getString("sdate");
                    quali=rs.getString("quali");
                    usrName=rs.getString("usrname");
                    passWrd=rs.getString("passwrd");
                    
                    
                   
                    
                    
                    
                    
        fnametxt.setText(fname);
        ininametxt.setText(ininame);
        nictxt.setText(nic);
        dobtxt.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(dob));
        jTextArea1.setText(addrs);
        dlicentxt.setText(licen);
        emailtxt.setText(email);
        lphonetxt.setText(lphone);
        mobiletxt.setText(mobile);
        agetxt.setText(age);
        sdatetxt.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(sdate));
        jTextArea2.setText(quali);
        jComboBox1.setSelectedItem(type);
        jComboBox2.setSelectedItem(sec);
        jComboBox3.setSelectedItem(desig);
        jTextField2.setText(usrName);
        jPasswordField1.setText(passWrd);
        jPasswordField2.setText(passWrd);
        
        
        if (gender.equals("Male"))
            jRadioButton1.setSelected(true);
        else
            jRadioButton2.setSelected(true);
        if (state.equals("Single"))
            jRadioButton3.setSelected(true);
        else
            jRadioButton4.setSelected(true);
        if (desig.equals("Worker"))
            passpanel.setVisible(false);
        else
            passpanel.setVisible(true);
        
        
       
        
        
       
                }
                }else{
                JOptionPane.showMessageDialog(null, "Couldn't done!", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_jTable1MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
//        gender = "Male";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
//        gender = "Female";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
//        state = "Single";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
//        state = "Married";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        
        String eid = jLabel15.getText();
        if(eid.equals("EID")){
        JOptionPane.showMessageDialog(null, "Pleace select a Employee!", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
        else{
        int x = JOptionPane.showConfirmDialog(null, "Do you want to delete this?");
        
        if(x==0){
            String id = jLabel15.getText();

            String sql = "DELETE FROM employee WHERE eid = '"+id+"'";

            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Succesfully deleted.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
            }

            jLabel12.setText(null);
            fnametxt.setText(null);
            ininametxt.setText(null);
            nictxt.setText(null);
            dobtxt.setDate(null);
            jTextArea1.setText(null);
            dlicentxt.setText(null);
            emailtxt.setText(null);
            lphonetxt.setText(null);
            mobiletxt.setText(null);
            agetxt.setText(null);
            sdatetxt.setDate(null);
            jTextArea2.setText(null);
            jComboBox1.setSelectedIndex(0);
            jComboBox2.setSelectedIndex(0);
            jComboBox3.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
           
        }

        //load table
        tableload();
        
        }
        
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
         jPanel13.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
       jPanel13.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel13MouseExited

    private void jComboBox2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox2FocusGained
      jComboBox2.removeAllItems();
        //set values to section combobox from db
       try {
 
            String sql ="SELECT DISTINCT sec_name FROM section "; 
            pst = con.prepareStatement(sql);
           
            rs =pst.executeQuery();
            
             while(rs.next()){
                 
                 String sec=rs.getString("sec_name");
                 jComboBox2.addItem(sec);
             }
             
    
       }
       catch(Exception e)
       {
           showMessageDialog(null,e, "Error", JOptionPane.ERROR_MESSAGE);
       }
        
    }//GEN-LAST:event_jComboBox2FocusGained

    private void fnametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnametxtFocusLost
      String name=fnametxt.getText();
        if(!name.isEmpty())
        {
            
            for(int x=0;x<name.length();x++)
            {   
                 if(name.charAt(x)==' ')
                {
                }
                 
               else if(!Character.isLetter(name.charAt(x)))
                {
                    showMessageDialog(null,"Only Letters are allowed", "Error", JOptionPane.ERROR_MESSAGE);
                   fnametxt.setText(null);
                    break;
                }
               
            }
            

        }
    }//GEN-LAST:event_fnametxtFocusLost

    private void ininametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ininametxtFocusLost
        String name=ininametxt.getText();
        if(!name.isEmpty())
        {
            
            for(int x=0;x<name.length();x++)
            {   
                 if(name.charAt(x)==' ')
                {
                }
                 
               else if(!Character.isLetter(name.charAt(x)))
                {
                    showMessageDialog(null,"Only Letters are allowed", "Error", JOptionPane.ERROR_MESSAGE);
                   ininametxt.setText(null);
                    break;
                }
               
            }
            

        }
    }//GEN-LAST:event_ininametxtFocusLost

    private void nictxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nictxtFocusLost
       String nic = nictxt.getText();
        
        if (!nic.isEmpty()){
                  
                
            if((nic.length()<10))
               {
                    showMessageDialog(null,"Not enough digits for NIC number", "Error", JOptionPane.ERROR_MESSAGE);
                    nictxt.setText(null);
                    
                }
                  
            else if((nic.length()>10))
               {
                    showMessageDialog(null,"No more than 10 digits for NIC number", "Error", JOptionPane.ERROR_MESSAGE);
                    nictxt.setText(null);
               }
                    else if(checknic(nic) == 0)//call checknic method
                    {
                    showMessageDialog(null,"First 9 characters should be numbers!", "Error", JOptionPane.ERROR_MESSAGE);
                    nictxt.setText(null);
                    
            }
        
            else if (nic.charAt(9)!='v' && nic.charAt(9)!='V')
                {
                   showMessageDialog(null,"Invalied NIC number", "Error", JOptionPane.ERROR_MESSAGE); 
                }
                
        
            else if(nic.length()==10){
                String nid=null;
        
         try {
           
                        String sql ="SELECT * FROM employee  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            nid=rs.getString("nic");
                            
                            if(nic.equals(nid)){
                                showMessageDialog(null,"This NIC number is already in database!", "Error", JOptionPane.ERROR_MESSAGE);
                                nictxt.setText(null);}
                            }
                        }
                    catch(Exception e)
                    {
                        showMessageDialog(null, e , "Error" , JOptionPane.ERROR_MESSAGE);
                    } 
        
       }
        }
    }//GEN-LAST:event_nictxtFocusLost

    private void dlicentxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dlicentxtFocusLost
       String dlicen = dlicentxt.getText();
        
        if(!dlicen.isEmpty()){
        if ((!Character.isLetter(dlicen.charAt(0))))
                {
                   showMessageDialog(null,"Invalied Licence no", "Error", JOptionPane.ERROR_MESSAGE); 
                   dlicentxt.setText(null);
                }
        else if (checklicen(dlicen)==0)//call checklicen method
          {
                 
                    showMessageDialog(null,"Letters are not allowed except first character!", "Error", JOptionPane.ERROR_MESSAGE);
                    dlicentxt.setText(null);
                      
        }
        else if((dlicen.length()<8))
               {
                    showMessageDialog(null,"Not enough digits for licence number", "Error", JOptionPane.ERROR_MESSAGE);
                    dlicentxt.setText(null);
                    
                }
          
         else if((dlicen.length()>8))
               {
                    showMessageDialog(null,"No more than 8 digits for licence number", "Error", JOptionPane.ERROR_MESSAGE);
                    dlicentxt.setText(null);
                    
                }
        
        }
    }//GEN-LAST:event_dlicentxtFocusLost

    private void lphonetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lphonetxtFocusLost
       String lphone = lphonetxt.getText();
        
        if(!lphone.isEmpty()){
        if(isnum(lphone)==0) //isnum method
                {
                    showMessageDialog(null,"Letters are not allowed in land phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    lphonetxt.setText(null);
                }
        else if((lphone.length()<10))
                {
                    showMessageDialog(null,"Not enough digits in land phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    lphonetxt.setText(null);
                }
        else if((lphone.length()>10))
                {
                    showMessageDialog(null,"Only 10 digits allowed in land phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    lphonetxt.setText(null);
                }
        }
    }//GEN-LAST:event_lphonetxtFocusLost

    private void mobiletxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobiletxtFocusLost
       String mobile = mobiletxt.getText();
       
       if(!mobile.isEmpty()){ 
       if(isnum(mobile)==0) //isnum method
                {
                    showMessageDialog(null,"Letters are not allowed in mobile phone Number", "Error", JOptionPane.ERROR_MESSAGE);
                    mobiletxt.setText(null);
                }
        else if((mobile.length()<10))
                {
                    showMessageDialog(null,"Not enough digits in mobile phone Number","Error", JOptionPane.ERROR_MESSAGE);
                    mobiletxt.setText(null);
                }
        else if((mobile.length()>10))
                {
                    showMessageDialog(null,"Only 10 digits allowed in mobile phone Number","Error", JOptionPane.ERROR_MESSAGE);
                    mobiletxt.setText(null);
                }
       }
    }//GEN-LAST:event_mobiletxtFocusLost

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost
       String email = emailtxt.getText();
        if(!email.isEmpty()){
        
        if(checkemail()==0)//checkmail method
                {
                   showMessageDialog(null,"Invalied email", "Error", JOptionPane.ERROR_MESSAGE);
                   emailtxt.setText(null);
              } 
        }
    }//GEN-LAST:event_emailtxtFocusLost

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String Passpanel = jComboBox3.getSelectedItem().toString();
        
        if(Passpanel == "Worker"){
        passpanel.setVisible(false);
        }
        else{
        passpanel.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        String usr = jTextField2.getText();
        
        if (!usr.isEmpty()){
                  
                try {
           
                        String sql ="SELECT * FROM employee  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            String Usrname=rs.getString("usrname");
                            
                            if(usr.equals(Usrname)){
                                showMessageDialog(null,"This username already in use. Please enter different username!", "Error", JOptionPane.ERROR_MESSAGE);
                                jTextField2.setText(null);}
                            }
                        }
                    catch(Exception e)
                    {
                        showMessageDialog(null, e , "Error" , JOptionPane.ERROR_MESSAGE);
                    } 
        
       }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
       
        String pass = jPasswordField1.getText();
        
        if (!pass.isEmpty()){
                  
                try {
           
                        String sql ="SELECT * FROM employee  "; 
                        pst = con.prepareStatement(sql);
                        rs =pst.executeQuery();
                        
                        while(rs.next()){
                            String Passwrd=rs.getString("passwrd");
                            
                            if(pass.equals(Passwrd)){
                                showMessageDialog(null,"Password in use!", "Error", JOptionPane.ERROR_MESSAGE);
                                jPasswordField1.setText(null);}
                            }
                        }
                    catch(Exception e)
                    {
                        showMessageDialog(null, e , "Error" , JOptionPane.ERROR_MESSAGE);
                    } 
        
       }
        
        
    }//GEN-LAST:event_jPasswordField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(up_del_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(up_del_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(up_del_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(up_del_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new up_del_Emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField dlicentxt;
    private com.toedter.calendar.JDateChooser dobtxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JTextField ininametxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lphonetxt;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nictxt;
    private javax.swing.JPanel passpanel;
    private com.toedter.calendar.JDateChooser sdatetxt;
    // End of variables declaration//GEN-END:variables
}
