    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory1;
//import DbConn.dbconnect;
//import static DbConn.dbconnect.connect;


//import static DbConn.dbconnect.connect;
import db_connect.dbconnect;
import static db_connect.dbconnect.connect;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Dharshika
 */
public class Billsofmaterials extends javax.swing.JFrame {
 Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;

    /**
     * Creates new form Billsofmaterials
     */
    public Billsofmaterials() {
    con= dbconnect.connect();
    
    
         initComponents();
         fillcombo ();
         fillfabcombo();
         showjTable();
    }
      private void fillcombo ()
    
            
    {
        try {
            
            
            String sql ="Select * from products";
            pst=con.prepareStatement(sql);
            rs =pst.executeQuery();
            while(rs.next())
            
            {
                
                
                String cat = rs.getNString("procode");
                cmb_productcode.addItem(cat);
            
            
            }
            
        } catch (Exception e) {
        }
        
        
        
    }
         void loadSubCat()
    {
        try {
             
            String sql ="Select * from products where procode ='"+cmb_productcode.getSelectedItem().toString()+"' ";
            pst1=con.prepareStatement(sql);
            rs1 =pst1.executeQuery();
            while(rs1.next())
            
            {
                
                
                String procategory = rs1.getNString("procategory");
                String subprocategory=rs1.getNString("prosubcategory");
                String size=rs1.getNString("size");
                String color=rs1.getNString("color");
                
                txt_procategory.setText(procategory);
                txt_prosubcategory.setText(subprocategory);
                txt_size.setText(size);
                txt_color.setText(color);
               
                
            
            }   
                
            
        } catch (Exception e) {
        }
    }
   private void fillfabcombo()
    
            
    {
        try {
            
            
            String sql ="Select * from rawmaterials where name LIKE '%Fabric%'";
            pst2=con.prepareStatement(sql);
            rs2 =pst2.executeQuery();
            while(rs2.next())
            
            {
                
                
                int fabbcode = rs2.getInt("code");
                String fabcode=Integer.toString(fabbcode);
                cmb_fabbcode.addItem(fabcode);
               
            
            
            }
            
        } catch (Exception e) {
        }
        
        
        
    } /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fabcolor = new javax.swing.JTextField();
        txt_unitproduct = new javax.swing.JTextField();
        cmb_productcode = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl_billno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_procategory = new javax.swing.JTextField();
        txt_prosubcategory = new javax.swing.JTextField();
        txt_fabricname = new javax.swing.JTextField();
        cmb_fabbcode = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_bill = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 610));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bill of Materials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subcategory");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");

        txt_size.setBackground(new java.awt.Color(153, 153, 153));

        txt_color.setBackground(new java.awt.Color(153, 153, 153));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fabric Code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fabric Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fabric Color");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Units/Product");

        txt_fabcolor.setBackground(new java.awt.Color(153, 153, 153));

        txt_unitproduct.setBackground(new java.awt.Color(153, 153, 153));

        cmb_productcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_productcodeActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lbl_billno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_billno.setForeground(new java.awt.Color(255, 255, 255));
        lbl_billno.setText("Bill No");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_procategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_procategoryActionPerformed(evt);
            }
        });

        txt_prosubcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prosubcategoryActionPerformed(evt);
            }
        });

        cmb_fabbcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_fabbcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(lbl_billno))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmb_productcode, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_color, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addComponent(txt_prosubcategory, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_procategory, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_size, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel11)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_unitproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_fabcolor)
                                .addComponent(txt_fabricname)
                                .addComponent(cmb_fabbcode, 0, 204, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbl_billno)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel9)
                                .addComponent(cmb_productcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_procategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_prosubcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(cmb_fabbcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_fabricname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fabcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_unitproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        jTable_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No", "Product Code", "Product Category", "Subcategory", "Size", "Product Color", "Fabric Code", "Fabric Name", "Fabric Color", "Units/Product"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_bill);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
      
        
        String query="INSERT INTO `billofmaterials`(`procode`, `procategory`, `prosubcategory`, `size`,`color`,`fabcode`,`fabname`,`fabcolor`,`unitproduct`) " + "VALUES ( '"+cmb_productcode.getSelectedItem()+"' ,'"+txt_procategory.getText()+"', '"+txt_prosubcategory.getText()+"','"+txt_size.getText()+"','"+txt_color.getText()+"','"+cmb_fabbcode.getSelectedItem()+"','"+txt_fabricname.getText()+"','"+txt_fabcolor.getText()+"','"+txt_unitproduct.getText()+"')";
        executeSqlQuery(query, "Insert");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String query="DELETE FROM `billofmaterials` WHERE `billno`='"+lbl_billno.getText()+"'";
        executeSqlQuery(query, "Delete");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String query="UPDATE `billofmaterials` SET `procategory`='"+cmb_productcode.getSelectedItem()+"',`prosubcategory`='"+txt_prosubcategory.getText()+"',`fabname`='"+txt_fabricname.getText()+"',`unitproduct`='"+txt_unitproduct.getText()+"'WHERE `billno`='"+lbl_billno.getText()+"'";
        executeSqlQuery(query, "Update");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmb_productcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_productcodeActionPerformed
       loadSubCat();
    }//GEN-LAST:event_cmb_productcodeActionPerformed

    private void jTable_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_billMouseClicked
         int i=jTable_bill.getSelectedRow();
        TableModel model=jTable_bill.getModel();
        
       lbl_billno.setText(model.getValueAt(i, 0).toString());
        cmb_productcode.setSelectedItem(model.getValueAt(i, 1).toString());
        txt_procategory.setText(model.getValueAt(i, 2).toString());
        txt_prosubcategory.setText(model.getValueAt(i, 3).toString());
        txt_size.setText(model.getValueAt(i, 4).toString());
        txt_color.setText(model.getValueAt(i, 5).toString());
        cmb_fabbcode.setSelectedItem(model.getValueAt(i, 6).toString());
        txt_fabcolor.setText(model.getValueAt(i, 8).toString());
        txt_fabricname.setText(model.getValueAt(i, 7).toString());
       
        txt_unitproduct.setText(model.getValueAt(i, 9).toString());
    }//GEN-LAST:event_jTable_billMouseClicked

    private void txt_procategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_procategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_procategoryActionPerformed

    private void txt_prosubcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prosubcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prosubcategoryActionPerformed

    private void cmb_fabbcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_fabbcodeActionPerformed
         try {
             
            String sql ="Select * from rawmaterials where code ='"+cmb_fabbcode.getSelectedItem().toString()+"' ";
            pst1=con.prepareStatement(sql);
            rs1 =pst1.executeQuery();
            while(rs1.next())
            
            {
                
                
                String name = rs1.getNString("name");
                String color=rs1.getNString("color");
               
                
                txt_fabcolor.setText(color);
                txt_fabricname.setText(name);
                
               
                
            
            }   
                
            
        } catch (Exception e) {
        }// TODO add your handling code here:
    }//GEN-LAST:event_cmb_fabbcodeActionPerformed
   public ArrayList<BillofmaterialsModel> getbillList()
    {
        ArrayList<BillofmaterialsModel> billlist=new ArrayList<>();
        Connection connection = connect();
        String query="Select * from billofmaterials";
        
        Statement st;
        ResultSet rs;
        
        try {
            st=connection.createStatement();
            rs=st.executeQuery(query);
           BillofmaterialsModel billmodel;
            
            while(rs.next())
            {
                
                
                billmodel=new  BillofmaterialsModel(rs.getInt("billno"),rs.getString("procode"), rs.getString("procategory"), rs.getString("prosubcategory"), rs.getString("size"), rs.getString("color"), rs.getInt("fabcode"),rs.getString("fabname"),rs.getString("fabcolor"), rs.getDouble("unitproduct"));
                billlist.add(billmodel);
            }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return billlist;
    }
      public void showjTable()
    {
        ArrayList<BillofmaterialsModel> listdata=getbillList();
        DefaultTableModel model =(DefaultTableModel)jTable_bill.getModel();
        
        Object [] row=new Object[10];
        for(int i = 0;i<listdata.size();i++)
        {
            
            row[0]=listdata.get(i).getBillno();
            row[1]=listdata.get(i).getProcode();
            row[2]=listdata.get(i).getProcategory();
            row[3]=listdata.get(i).getProsubcategory();
            row[4]=listdata.get(i).getSize();
            row[5]=listdata.get(i).getColor();
            row[6]=listdata.get(i).getFabcode();
            row[7]=listdata.get(i).getFabname();
           row[8]=listdata.get(i).getFabcolor();
           row[9]=listdata.get(i).getUnitprodct();
          
          
            
            model.addRow(row);
        }
    
    }
      
          public void ClearField()
    {
       
        
        lbl_billno.setText(null);
        cmb_productcode.setSelectedItem(null);
       // cmb_productcode.setSelectedItem(null);
        //cmb_prosubcategory.setSelectedItem(null);
        txt_procategory.setText(null);
        txt_prosubcategory.setText(null);
        txt_size.setText(null);
        txt_color.setText(null);
        cmb_fabbcode.setSelectedItem(null);
       // cmb_fabcode.setSelectedItem(null);
       txt_fabricname.setText(null);
        txt_fabcolor.setText(null);
        txt_unitproduct.setText(null);
          
        
    }
       public void executeSqlQuery(String query,String message)
     {
         Connection conn= connect();
         Statement st;
         try {
              st=con.createStatement();
              if((st.executeUpdate(query))==1)
              {
                  // data get refresh after query runs 
                  DefaultTableModel model = (DefaultTableModel)jTable_bill.getModel();
                  model.setRowCount(0);
                  showjTable();
                  
                  
                  // message box
                  JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
                  ClearField();
              }else{
                  JOptionPane.showMessageDialog(null, "Data "+message+" Failed");
              }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
         }
     
     }
     
     
     
     
      
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billsofmaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billsofmaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billsofmaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billsofmaterials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billsofmaterials().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_fabbcode;
    private javax.swing.JComboBox<String> cmb_productcode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_bill;
    private javax.swing.JLabel lbl_billno;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_fabcolor;
    private javax.swing.JTextField txt_fabricname;
    private javax.swing.JTextField txt_procategory;
    private javax.swing.JTextField txt_prosubcategory;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_unitproduct;
    // End of variables declaration//GEN-END:variables
}
