/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory1;

import Inventory1.Orders;
//import dbConnect.dbcon;
import db_connect.dbconnect;
import static db_connect.dbconnect.connect;

import java.awt.Color;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**

/**
 *
 * @author Dharshika
 */
public class Checkbills extends javax.swing.JFrame {
 String procode;
    String fabcode;
    String orderproducts;
    String orderno;
     Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    /**
     * Creates new form Checkbills
     */
    public Checkbills() {
    initComponents();
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    }
    public Checkbills(String y,String z,String p,String a)
{
    
        initComponents();
         con= dbconnect.connect();
        
      
     
     try {
         
         orderno=a;
         procode=y;
        fabcode=z;
        orderproducts=p;
       
        
        
                
        
     lbl_procode.setText(procode);
     lbl_fabcode.setText(fabcode);
     txt_orderproducts.setText(orderproducts);
     lbl_orderno.setText(orderno);
          
        
           
            
            Connection connection = connect();	
            Statement st = connection.createStatement();
          //Statement st1 = connection.createStatement();
            ResultSet rs ;
           
              int fabriccode =Integer.parseInt(lbl_fabcode.getText());
            
             rs = st.executeQuery("select * from billofmaterials where procode='"+lbl_procode.getText()+"' AND fabcode='"+fabriccode+"'" );
            // ResultSet rs1;
                        //  rs1 = st1.executeQuery("select * from rawmaterials where code='"+fabriccode+"'" );
  
             
                        String procategory = "";
                         String prosubcategory = "";
                          String size = "";
                           String color = "";
                            String fabname = "";
                             String fabcolor = "";
                             String unitproduct="";
                           // String av="";
                            while(rs.next()){

                                                
                                              
                                                procategory = rs.getString("procategory");
                                                   prosubcategory = rs.getString("prosubcategory");
                                                      size = rs.getString("size");
                                                         color = rs.getString("color");
                                                                fabname = rs.getString("fabname");
                                                              fabcolor = rs.getString("fabcolor");
                                                              unitproduct =Double.toString(rs.getDouble("unitproduct"));
                                                
                                            }
                             
//                             while(rs1.next()){
//                                 
//                                  //av =Double.toString(rs.getDouble("stockqty"));
//                                 
//                                 
//                             }
                            
                            
          
            txt_procategory.setText(procategory);
            txt_prosubcategory.setText(prosubcategory);
            txt_size.setText(size);
            txt_color.setText(color);
            txt_fabname.setText(fabname);
            txt_fabcolor.setText(fabcolor);
            txt_unitproduct.setText(unitproduct);
          // txt_availablefabric.setText(av);
                      
            
           
          
    } catch (Exception e) {
    }
     
     
        
          

}  
   
    
    
    
    
    /**
 
 
 
 
 * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_procode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_size = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        lbl_fabcode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_fabcolor = new javax.swing.JTextField();
        txt_unitproduct = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_availablefabric = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_made = new javax.swing.JTextField();
        txt_fabname = new javax.swing.JTextField();
        txt_procategory = new javax.swing.JTextField();
        txt_prosubcategory = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_orderproducts = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panel_confirmorder = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_neededfabric = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lbl_orderno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 610));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Bill of Materials", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lbl_procode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_procode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_procode.setText("Product code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subcategory");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Size");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");

        txt_size.setBackground(new java.awt.Color(204, 204, 204));
        txt_size.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_color.setBackground(new java.awt.Color(204, 204, 204));
        txt_color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_fabcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_fabcode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fabcode.setText("Fabric Code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fabric Name");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fabric Color");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Units/Product");

        txt_fabcolor.setBackground(new java.awt.Color(204, 204, 204));
        txt_fabcolor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_unitproduct.setBackground(new java.awt.Color(204, 204, 204));
        txt_unitproduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_unitproduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_unitproductKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Available Fabric");

        txt_availablefabric.setBackground(new java.awt.Color(204, 204, 204));
        txt_availablefabric.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_availablefabric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_availablefabricMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Products can be made");

        txt_made.setBackground(new java.awt.Color(204, 204, 204));
        txt_made.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_made.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_madeMouseClicked(evt);
            }
        });
        txt_made.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_madeKeyPressed(evt);
            }
        });

        txt_fabname.setBackground(new java.awt.Color(204, 204, 204));
        txt_fabname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_procategory.setBackground(new java.awt.Color(204, 204, 204));
        txt_procategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_prosubcategory.setBackground(new java.awt.Color(204, 204, 204));
        txt_prosubcategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Meter");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Products needed for Orders");

        txt_orderproducts.setBackground(new java.awt.Color(204, 204, 204));
        txt_orderproducts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_orderproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_orderproductsMouseClicked(evt);
            }
        });
        txt_orderproducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_orderproductsKeyPressed(evt);
            }
        });

        panel_confirmorder.setBackground(new java.awt.Color(51, 51, 51));
        panel_confirmorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel_confirmorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_confirmorderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_confirmorderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_confirmorderMouseExited(evt);
            }
        });
        panel_confirmorder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Confirm Order");
        panel_confirmorder.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Needed Fabric ");

        txt_neededfabric.setBackground(new java.awt.Color(204, 204, 204));
        txt_neededfabric.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_neededfabric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_neededfabricMouseClicked(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Meter");

        lbl_orderno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_orderno.setForeground(new java.awt.Color(255, 255, 255));
        lbl_orderno.setText("Order No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_orderno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_procode)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_size, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(txt_color)
                                    .addComponent(txt_procategory, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(txt_prosubcategory, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_orderproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(lbl_fabcode)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel14))))
                                    .addGap(48, 48, 48)))
                            .addComponent(jLabel12))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_fabcolor, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(txt_availablefabric)
                                    .addComponent(txt_unitproduct)
                                    .addComponent(txt_fabname)
                                    .addComponent(txt_neededfabric, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel15))
                                .addGap(210, 210, 210))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_made, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_confirmorder, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_orderno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_procode)
                    .addComponent(lbl_fabcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_procategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_prosubcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_fabname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_fabcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_unitproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txt_availablefabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_orderproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_neededfabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_made, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(22, 22, 22)
                                        .addComponent(panel_confirmorder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_unitproductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_unitproductKeyReleased
        
        
                                     
    
    }//GEN-LAST:event_txt_unitproductKeyReleased

    private void txt_availablefabricMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_availablefabricMouseClicked
       con= dbconnect.connect();
        String fabcode =lbl_fabcode.getText();
        
        Integer code =Integer.parseInt(fabcode);
        
        try {
            
            
            
             Connection connection = connect();	
            Statement st = connection.createStatement();
          
            ResultSet rs ;
           
             
            
            
                         rs = st.executeQuery("select * from rawmaterials where code='"+code+"'" );
  
             
                            String av="";
                            while(rs.next()){

                                                
                                             
                                                              av =Double.toString(rs.getDouble("stockqty"));
                                                
                                            }
                             
                             
                            
                            
          
           
          txt_availablefabric.setText(av);
                      
            
           
          
    } catch (Exception e) {
    }
     
            
       
        
        
        
        
        
        
    }//GEN-LAST:event_txt_availablefabricMouseClicked

    private void txt_madeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_madeKeyPressed
//        Double available= Double.parseDouble(txt_availablefabric.getText());
//        Double unitproduct = Double.parseDouble(txt_unitproduct.getText());
////        try{
//                Double made = available+unitproduct;
//                String due = Double.toString(made);
//                txt_made.setText(due);
//                            
//                    }catch(Exception ex){
//                    }
    }//GEN-LAST:event_txt_madeKeyPressed

    private void txt_madeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_madeMouseClicked
         Double available= Double.parseDouble(txt_availablefabric.getText());
        Double unitproduct = Double.parseDouble(txt_unitproduct.getText());
//        try{
                Double made = available/unitproduct;
                Integer i = made.intValue();
                String due = Integer.toString(i);
                txt_made.setText(due);
    }//GEN-LAST:event_txt_madeMouseClicked

    private void txt_orderproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_orderproductsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_orderproductsMouseClicked

    private void txt_orderproductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_orderproductsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_orderproductsKeyPressed

    private void panel_confirmorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_confirmorderMouseClicked
        double orderproducts = Double.parseDouble(txt_orderproducts.getText());
        double made = Double.parseDouble(txt_made.getText());
  
      if(made>=orderproducts){
       
           
                    Finalorder sp1 = new Finalorder ();
                    sp1.setVisible(true);
                    
                    String procode=lbl_procode.getText();
                    String fabriccode=lbl_fabcode.getText();
                    String available = txt_availablefabric.getText();
                    String neededfabric=txt_neededfabric.getText();
                    String productneeded=txt_orderproducts.getText();
                    String orderno=lbl_orderno.getText();
                    String fabname=txt_fabname.getText();
           Finalorder sp = new Finalorder (procode,fabriccode,available,neededfabric,productneeded,orderno,fabname);
           sp.setVisible(true);
        
       
       }
       else{
       showMessageDialog(null,"Can't confirm order please purchase!", "Error", JOptionPane.ERROR_MESSAGE);
       
       Purchases ra = new Purchases();
        ra.setVisible(true);
        String fabname=txt_fabname.getText();
       Purchases r = new Purchases(fabname);
        r.setVisible(true);
       
       }
    }//GEN-LAST:event_panel_confirmorderMouseClicked

    private void panel_confirmorderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_confirmorderMouseEntered
        panel_confirmorder.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_panel_confirmorderMouseEntered

    private void panel_confirmorderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_confirmorderMouseExited
        panel_confirmorder.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_panel_confirmorderMouseExited

    private void txt_neededfabricMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_neededfabricMouseClicked
        double unitproduct = Double.parseDouble(txt_unitproduct.getText());
        double orderproducts = Double.parseDouble(txt_orderproducts.getText());


            try{
                double fabricneeded=unitproduct*orderproducts;
                String fabric = String.valueOf(fabricneeded);
                txt_neededfabric.setText(fabric);
                            
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                                        }



// TODO add your handling code here:
    }//GEN-LAST:event_txt_neededfabricMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkbills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkbills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_fabcode;
    private javax.swing.JLabel lbl_orderno;
    private javax.swing.JLabel lbl_procode;
    private javax.swing.JPanel panel_confirmorder;
    private javax.swing.JTextField txt_availablefabric;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_fabcolor;
    private javax.swing.JTextField txt_fabname;
    private javax.swing.JTextField txt_made;
    private javax.swing.JTextField txt_neededfabric;
    private javax.swing.JTextField txt_orderproducts;
    private javax.swing.JTextField txt_procategory;
    private javax.swing.JTextField txt_prosubcategory;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_unitproduct;
    // End of variables declaration//GEN-END:variables
}
