/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory1;
import Inventory1.Purchases;
import db_connect.dbconnect;
import static db_connect.dbconnect.connect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Dharshika
 */
public class SupplierPayments extends javax.swing.JFrame {

       
    String suppid;
    String suppname;
    String totalcoast;
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    
    
    public SupplierPayments() {
    con= dbconnect.connect();
   
    initComponents();
        
         showjTable();
    }
    
    
    
    public SupplierPayments(String y,String z,String xx) {
       
        initComponents();
         con= dbconnect.connect();
         try {         
        suppid =y;
        suppname=z;
        totalcoast=xx;
        
        
                
        
        txt_paysuppid.setText(suppid);
        txt_paybusinessname.setText(suppname);
        txt_paytotalamount.setText(totalcoast);
        
          
            
            Connection connection = connect();	
            Statement st = connection.createStatement();
            ResultSet rs ;
             rs = st.executeQuery("select * from supplierpurchases where purchaseorderno= (select MAX(purchaseorderno) from supplierpurchases)");
             
                        String purchaseorderno = "";
            
                           

                            while(rs.next()){

                                                
                                              
                                                purchaseorderno = rs.getString("purchaseorderno");
                                                
                                            }
           
            txt_paypurchaseno.setText(purchaseorderno);
                     
            
            
            
        }
        catch (Exception e) {
        }
        
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_paypurchaseno = new javax.swing.JTextField();
        txt_paysuppid = new javax.swing.JTextField();
        txt_paybusinessname = new javax.swing.JTextField();
        cmb_paymenttype = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_paypaidamount = new javax.swing.JTextField();
        txt_paydueamount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_paytotalamount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_payid = new javax.swing.JLabel();
        date_paymentdate = new com.toedter.calendar.JDateChooser();
        add = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cancle = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        refresh1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_payment = new javax.swing.JTable();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(230, 150));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 610));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Supplier Business Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Payment Type");

        txt_paypurchaseno.setBackground(new java.awt.Color(153, 153, 153));
        txt_paypurchaseno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_paysuppid.setBackground(new java.awt.Color(153, 153, 153));
        txt_paysuppid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_paybusinessname.setBackground(new java.awt.Color(153, 153, 153));
        txt_paybusinessname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cmb_paymenttype.setBackground(new java.awt.Color(153, 153, 153));
        cmb_paymenttype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_paymenttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Cash", "Cheque", "Deposit" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Paid Amount");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Due Amount");

        txt_paypaidamount.setBackground(new java.awt.Color(153, 153, 153));
        txt_paypaidamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_paypaidamount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_paypaidamountFocusLost(evt);
            }
        });
        txt_paypaidamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paypaidamountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_paypaidamountKeyTyped(evt);
            }
        });

        txt_paydueamount.setBackground(new java.awt.Color(153, 153, 153));
        txt_paydueamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Order No");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Payment Date");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total amount");

        txt_paytotalamount.setBackground(new java.awt.Color(153, 153, 153));
        txt_paytotalamount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment ID");

        lbl_payid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_payid.setForeground(new java.awt.Color(255, 255, 255));
        lbl_payid.setText("ID");

        add.setBackground(new java.awt.Color(51, 51, 51));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Add");

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel15)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        update.setBackground(new java.awt.Color(51, 51, 51));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Update");

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel17)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        delete.setBackground(new java.awt.Color(51, 51, 51));
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Delete");

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel20)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancle.setBackground(new java.awt.Color(51, 51, 51));
        cancle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        cancle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancleMouseExited(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Cancel");

        javax.swing.GroupLayout cancleLayout = new javax.swing.GroupLayout(cancle);
        cancle.setLayout(cancleLayout);
        cancleLayout.setHorizontalGroup(
            cancleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancleLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel25)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        cancleLayout.setVerticalGroup(
            cancleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        refresh1.setBackground(new java.awt.Color(51, 51, 51));
        refresh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        refresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refresh1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refresh1MouseExited(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Refresh");

        javax.swing.GroupLayout refresh1Layout = new javax.swing.GroupLayout(refresh1);
        refresh1.setLayout(refresh1Layout);
        refresh1Layout.setHorizontalGroup(
            refresh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refresh1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel23)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        refresh1Layout.setVerticalGroup(
            refresh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refresh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_payid)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(date_paymentdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_paybusinessname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_paysuppid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_paypurchaseno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_paymenttype, 0, 204, Short.MAX_VALUE)
                                    .addComponent(txt_paypaidamount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_paydueamount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_paytotalamount))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel11)))
                        .addGap(432, 432, 432))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_payid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paypurchaseno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paysuppid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_paybusinessname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_paymenttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_paymentdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paytotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paypaidamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_paydueamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        tbl_payment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Order No", "Supplier ID", "Supplier Business  Name", "Payment Type", "Payment Date", "Total amount", "Paid amount", "Due Amount"
            }
        ));
        tbl_payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_paymentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_payment);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_paypaidamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paypaidamountKeyReleased
        Double totalcost = Double.parseDouble(txt_paytotalamount.getText());
        Double paidamount = Double.parseDouble(txt_paypaidamount.getText());
        
         if(Validations.isnum(txt_paypaidamount.getText())==0) //isnum method
         {
            showMessageDialog(null,"Please enter number value !");
            txt_paypaidamount.setForeground(new Color(255,0,0));
            txt_paypaidamount.setForeground(new Color(255,0,0));
         }  
        try{
                Double dueamount=totalcost-paidamount;
                String due = String.valueOf(dueamount);
                txt_paydueamount.setText(due);
                            
                    }catch(Exception e){
                         JOptionPane.showMessageDialog(null, e);
                                        }
        
    }//GEN-LAST:event_txt_paypaidamountKeyReleased
    
     public ArrayList<Supplierpaymentsemodel> getSupplierPaymentsList()
    {
        ArrayList<Supplierpaymentsemodel> supplierPaymentsList=new ArrayList<>();
        Connection connection = connect();
        String query="Select * from supplierpayments";
        
        Statement st;
        ResultSet rs;
        
        try {
            st=connection.createStatement();
            rs=st.executeQuery(query);
            Supplierpaymentsemodel paymentmodel;
            
            while(rs.next())
            {
             paymentmodel=new Supplierpaymentsemodel(rs.getInt("paymentid"),rs.getInt("purchaseorderno"), rs.getInt("supplierid"),                 
                        rs.getString("businessname"), rs.getString("paymenttype"), rs.getDate("paymentdate"), 
                        rs.getDouble("totalamount"), rs.getDouble("paidamount"), rs.getDouble("dueamount"));
                
                        supplierPaymentsList.add(paymentmodel);
            }
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return supplierPaymentsList;
    }
      public void showjTable()
    {
        ArrayList<Supplierpaymentsemodel> listdata=getSupplierPaymentsList();
        DefaultTableModel model =(DefaultTableModel)tbl_payment.getModel();
        
        Object [] row=new Object[9];
        for(int i = 0;i<listdata.size();i++)
        {
            row[0]=listdata.get(i).getPaymentid();
            row[1]=listdata.get(i).getPurchaseorderno();
            row[2]=listdata.get(i).getSupplierid();
            row[3]=listdata.get(i).getBusinessname();
            row[4]=listdata.get(i).getPaymenttype();
            row[5]=listdata.get(i).getPaymentdate();
            row[6]=listdata.get(i).getTotalamount();
            row[7]=listdata.get(i).getDueamount();
            row[8]=listdata.get(i).getPaidamount();
            
            
            model.addRow(row);
        }
    
    }
   
    
    
    
    private void tbl_paymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_paymentMouseClicked
        
        
        int i=tbl_payment.getSelectedRow();
        TableModel model=tbl_payment.getModel();
        
       
        try { 
            
        lbl_payid.setText(model.getValueAt(i, 0).toString());
        txt_paypurchaseno.setText(model.getValueAt(i, 1).toString());
        txt_paysuppid.setText(model.getValueAt(i, 2).toString());
        txt_paybusinessname.setText(model.getValueAt(i, 3).toString());
        cmb_paymenttype.setSelectedItem(model.getValueAt(i, 4).toString());
        date_paymentdate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(i,5).toString()));
        txt_paytotalamount.setText(model.getValueAt(i, 6).toString());
        txt_paypaidamount.setText(model.getValueAt(i, 7).toString());
        txt_paydueamount.setText(model.getValueAt(i, 8).toString());
            
        } catch (Exception e) {
        }
       
        
        
        
        
      
       
    }//GEN-LAST:event_tbl_paymentMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

       
            int x = JOptionPane.showConfirmDialog(null,"Do you want to add new record?");

            if(x==0)
            {
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        String query = "INSERT INTO `supplierpayments`(`purchaseorderno`,`supplierid`,`businessname`,`paymenttype`,`paymentdate`,`totalamount`,`paidamount`,`dueamount`)VALUES ('" + txt_paypurchaseno.getText() + "','" + txt_paysuppid.getText() + "','" + txt_paybusinessname.getText() + "','" + cmb_paymenttype.getSelectedItem() + "','" + dateFormat.format(date_paymentdate.getDate()) + "','" + txt_paytotalamount.getText() + "','" + txt_paypaidamount.getText() + "','" + txt_paydueamount.getText() + "')";

        executeSqlQuery(query, "Insert");

            }
            else if( x==1) {

                ClearField();
            }
        
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_addMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        int x = JOptionPane.showConfirmDialog(null,"Do you want to add new record?");
        if(x==0)
        {

             String query="UPDATE `supplierpayments` SET `paymenttype`='"+cmb_paymenttype.getSelectedItem()+"', `paymentdate`='"+dateFormat.format(date_paymentdate.getDate())+"',`totalamount`='"+txt_paytotalamount.getText()+"',`paidamount`='"+txt_paydueamount.getText()+"',`dueamount`='"+txt_paydueamount.getText()+"'WHERE `paymentid`='"+lbl_payid.getText()+"'";
        executeSqlQuery(query, "Update");
        

        }
        else if( x==1) {

            ClearField();
        }
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        update.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_updateMouseExited

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        //delete
        int x = JOptionPane.showConfirmDialog(null,"Do you want to add new record?");

        if(x==0)
        {
  String query="DELETE FROM `supplierpayments` WHERE `paymentid`='"+lbl_payid.getText()+"'";
       executeSqlQuery(query, "Delete");

        }
        else if( x==1) {

            ClearField();
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_deleteMouseExited

    private void cancleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancleMouseClicked

    private void cancleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleMouseEntered
        cancle.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_cancleMouseEntered

    private void cancleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancleMouseExited
        cancle.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_cancleMouseExited

    private void refresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh1MouseClicked
        ClearField();
    }//GEN-LAST:event_refresh1MouseClicked

    private void refresh1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh1MouseEntered
        refresh1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_refresh1MouseEntered

    private void refresh1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh1MouseExited
        refresh1.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_refresh1MouseExited

    private void txt_paypaidamountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_paypaidamountFocusLost
        
         double qty = Double.parseDouble(txt_paypaidamount.getText());
       
  
  if(Validations.minus(qty)==0) 
         {
            showMessageDialog(null,"Negative value not allowed !");
            txt_paypaidamount.setForeground(new Color(255,0,0));
            txt_paypaidamount.setForeground(new Color(255,0,0));
         }  
        if(Validations.isnum(txt_paypaidamount.getText())==0) //isnum method
         {
            showMessageDialog(null,"Please enter number value !");
            txt_paypaidamount.setForeground(new Color(255,0,0));
            txt_paypaidamount.setForeground(new Color(255,0,0));
         } 
        
    }//GEN-LAST:event_txt_paypaidamountFocusLost

    private void txt_paypaidamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paypaidamountKeyTyped
        txt_paypaidamount.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_txt_paypaidamountKeyTyped
 
     public void executeSqlQuery(String query,String message)
     {
         Connection conn= connect();
         Statement st;
         try {
              st=con.createStatement();
              if((st.executeUpdate(query))==1)
              {
                  // data get refresh after query runs 
                  DefaultTableModel model = (DefaultTableModel)tbl_payment.getModel();
                  model.setRowCount(0);
                  showjTable();
                                    
                  // message box
                  JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
                  ClearField();
              }else{
                  JOptionPane.showMessageDialog(null, "Data "+message+" Failed");
              }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
            
         }
         
     }
    
    
    
    public void ClearField()
    {
        
        txt_paybusinessname.setText(null);
        cmb_paymenttype.setSelectedItem(null);
        txt_paydueamount.setText(null);
        txt_paypaidamount.setText(null);
        txt_paypurchaseno.setText(null);
        txt_paysuppid.setText(null);
        txt_paytotalamount.setText(null);
       date_paymentdate.setDate(null); 
   }
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierPayments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JPanel cancle;
    private javax.swing.JComboBox cmb_paymenttype;
    private com.toedter.calendar.JDateChooser date_paymentdate;
    private javax.swing.JPanel delete;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_payid;
    private javax.swing.JPanel refresh1;
    private javax.swing.JTable tbl_payment;
    private javax.swing.JTextField txt_paybusinessname;
    private javax.swing.JTextField txt_paydueamount;
    private javax.swing.JTextField txt_paypaidamount;
    private javax.swing.JTextField txt_paypurchaseno;
    private javax.swing.JTextField txt_paysuppid;
    private javax.swing.JTextField txt_paytotalamount;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
