package delivery.management;


import delivery.management.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.ZonedDateTime;
import javax.swing.JOptionPane;
import db_connect.dbconnect;
import static javax.swing.JOptionPane.showMessageDialog;
import net.proteanit.sql.DbUtils;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asd
 */
public class DeliveryAssignment extends javax.swing.JFrame {

        Connection con=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
        
        String DeliveryID;
        String OrederID;
        String HandlingDate;
        String Style ;
        String TotalPieces; 
        String VID;
        String Destination;
        String Shipdate;
        String DriverId;
        String Maxweight;
        String DeliveryStatus;
        
        boolean trueoid;
        boolean truevid;
    /**
     * Creates new form DeliveryAssignment
     */
    public DeliveryAssignment() {
        initComponents();
        con= dbconnect.connect();
        tableload();
        loadDriverID();
    }
    
    public void loadDriverID()
    {
        //jComboBox1.removeAllItems();
        try{
            String sql= "SELECT DriverId FROM adddriver";
            pst = con.prepareStatement(sql);
            
            rs = pst.executeQuery();
            
            while(rs.next())
            {
            String DiD=rs.getString("DriverId");
            jComboBox1.addItem(DiD);
            }
        }
        catch(Exception E)
        {
            System.out.println(E);
        }
    }
    public void tableload()
    {
       try {
 
            String sql ="SELECT DeliveryId as DeliveryId,OrderId as OrderID,Vid as VehicleId , Destination as Destination , HandlingDAte as HandlingDate , ShipDate as ShipDate , DriverId as DriverId , Style as Style , Maxweight as Maxweight , TotalPieces as TotalPieces , DeliveryStatus as DeliveryStatus FROM DeliveryAssignment "; 
            pst = con.prepareStatement(sql);
           
            rs =pst.executeQuery();
            
              table.setModel(DbUtils.resultSetToTableModel(rs));      
       }
       catch(Exception e)
       {
           showMessageDialog(null,e);
       }
       
      
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void reset()
    {
        oid.setText(null);
        jDateChooser1.setDate(null);
        deID.setText(null);
        styl.setText(null);
        TotPiece.setText(null);
        desti.setSelectedItem(0);
        jDateChooser2.setDate(null);
        Vid.setText(null);
        lw.setText(null);
        ds.setSelectedIndex(0);
        
    }
    void setTable()
    {
       String sql="select DeliveryId,VId,HandlingDate,ShipDate,Style,LoadWeight,TotalPieces,DeliveryStatus from deliveryassignment";
       
       try{
           pst=con.prepareStatement(sql);
           rs=pst.executeQuery();
           
           table.setModel(DbUtils.resultSetToTableModel(rs));
       }
       catch(Exception e)
       {
           
       }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        styl = new javax.swing.JTextField();
        lw = new javax.swing.JTextField();
        TotPiece = new javax.swing.JTextField();
        oid = new javax.swing.JTextField();
        deID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Vid = new javax.swing.JLabel();
        ds = new javax.swing.JComboBox();
        lable1 = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ser = new javax.swing.JTextField();
        lable3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        desti = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(222, 145));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setAlignmentX(2456666.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(2320, 556));
        jPanel1.setPreferredSize(new java.awt.Dimension(4, 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Delivery Assignment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 13, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Order ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Handling  Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ship Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Loading Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Style ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Pieces");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 85, 22));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("load Weight");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Delivery ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Delivery ID", "VehicleId", "MaxWeight", "ReqestedDate", "ShipDate", "Style", "loadWeight", "TotalPieces", "DeliveryStatus", "OrderId", "destination"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 840, 110));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DeliveryStatus");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        styl.setBackground(new java.awt.Color(153, 153, 153));
        styl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stylActionPerformed(evt);
            }
        });
        jPanel1.add(styl, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 122, -1));

        lw.setBackground(new java.awt.Color(153, 153, 153));
        lw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lwFocusLost(evt);
            }
        });
        jPanel1.add(lw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, -1));

        TotPiece.setBackground(new java.awt.Color(153, 153, 153));
        TotPiece.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TotPieceFocusLost(evt);
            }
        });
        jPanel1.add(TotPiece, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 122, -1));

        oid.setBackground(new java.awt.Color(153, 153, 153));
        oid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                oidKeyTyped(evt);
            }
        });
        jPanel1.add(oid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 65, -1));

        deID.setBackground(new java.awt.Color(153, 153, 153));
        deID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deIDActionPerformed(evt);
            }
        });
        jPanel1.add(deID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 170, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Destination");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Driver Id");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 90, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Add");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, 30));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Update");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Delete");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, 30));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Print");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel19)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel19))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));

        Vid.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(Vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 120, 30));

        ds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Not Shipped", "Handling", "Handled and not shipped", "Handled and shipped" }));
        jPanel1.add(ds, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, -1, -1));

        lable1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, 30));

        lable2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 180, 30));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("search");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 140, 30));

        ser.setBackground(new java.awt.Color(102, 102, 102));
        ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serActionPerformed(evt);
            }
        });
        jPanel1.add(ser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 130, 30));
        jPanel1.add(lable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 170, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 150, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/basic1-007_house_home-32.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 60, 60));

        desti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Katunayake", "Hambantota", "Colombo", "Mattala", " ", " " }));
        jPanel1.add(desti, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 150, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stylActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stylActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stylActionPerformed

    private void deIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deIDActionPerformed

    private void oidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oidKeyReleased
        // TODO add your handling code here:
              String sql="select * from ordermanagment where OrderId=?";
        
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,oid.getText());
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                styl.setText(rs.getString("Style"));
                TotPiece.setText(rs.getString("TotalPiecse"));
                lable1.setText(null);
                trueoid=true;
            }
            else if(oid.getText().length()>0)
            {
                lable1.setText("Inavalid Id");
                styl.setText(null);
                TotPiece.setText(null);
                trueoid=false;
            }
            else
            {
                styl.setText(null);
                TotPiece.setText(null);
                lable1.setText(null);
                
            }
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_oidKeyReleased

    private void oidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oidKeyTyped
        // TODO add your handling code here:
          
    }//GEN-LAST:event_oidKeyTyped

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        
        DeliveryID=deID.getText();
        OrederID=oid.getText();
        DriverId=jComboBox1.getSelectedItem().toString();
        Maxweight=lw.getText();
        Destination=desti.getSelectedItem().toString();
        HandlingDate=sd.format(jDateChooser1.getDate());
        Shipdate=sd.format(jDateChooser1.getDate());;
        VID=Vid.getText();
        Style=styl.getText();
        TotalPieces=TotPiece.getText();
        DeliveryStatus=ds.getSelectedItem().toString();
        
        String sql="INSERT INTO deliveryassignment(DeliveryId,OrderId,VID,Maxweight,Destination,HandlingDate,ShipDate,DriverId,Style,TotalPieces,DeliveryStatus)"
                    +" VALUES('"+DeliveryID+"','"+OrederID+"','"+VID+"','"+Maxweight+"','"+Destination+"','"+HandlingDate+"','"+Shipdate+"','"+DriverId+"','"+Style+"','"+TotalPieces+"','"+DeliveryStatus+"')";
        
        try{
            pst=con.prepareStatement(sql);
            
            if(trueoid==true && truevid==true)
            {
                pst.execute(sql);
                //setTable();
                reset();
                JOptionPane.showMessageDialog(null,"Success");
                tableload();
            }
            else if(trueoid==false && truevid==true)
            {
                JOptionPane.showMessageDialog(null,"Inavalid Oreder ID..");
            }
            else if(truevid==false && trueoid==true)
            {
                  JOptionPane.showMessageDialog(null,"Inavalid Vehicle ID..");
            }
            else
            {
                  JOptionPane.showMessageDialog(null,"Inavalid Order ID and vehicle ID..");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        
        String sql="update deliveryassignment set OrderId=?,VId=?,DriverId=?,Maxweight=?,Destination=?,HandlingDate=?,ShipDate=?,Style=?,TotalPieces=?,DeliveryStatus=? where DeliveryId=?";
        
        try{
            pst=con.prepareStatement(sql);
            
            pst.setString(1,oid.getText());    
            pst.setString(2,Vid.getText());
            pst.setString(3,jComboBox1.getSelectedItem().toString());
            pst.setString(4,lw.getText());
            pst.setString(5,desti.getSelectedItem().toString());
            pst.setString(6,sd.format(jDateChooser1.getDate()));
            pst.setString(7,sd.format(jDateChooser2.getDate()));
           
            pst.setString(8,styl.getText());
            pst.setString(9,TotPiece.getText());
            pst.setString(10,ds.getSelectedItem().toString());
            
            pst.setString(11,deID.getText());
            
            pst.executeUpdate();
            //setTable();
            reset();
            
            JOptionPane.showMessageDialog(null, "Successsfuly Updated");
            tableload();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Not Updated Successfuly");
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        int y=JOptionPane.showConfirmDialog(null,"Do you really want to delete?");
       
       if (y==0)
       {        
          try{
            String DeliveryId=deID.getText();
            String sql="delete from deliveryassignment where DeliveryId='"+DeliveryId+"'";
            pst=con.prepareStatement(sql);
            pst.execute();
            tableload();
            JOptionPane.showMessageDialog(null, "Successfuly deleted");
        }
       
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"unsuccessful Deletion");
        }
       }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        String sql="select * from  deliveryassignment where DeliveryId=?";
        
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,ser.getText());
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                deID.setText(rs.getString("DeliveryId"));
                oid.setText(rs.getString("OrderId"));
                jDateChooser1.setDate(rs.getDate("HandlingDate"));
                styl.setText(rs.getString("Style"));
                TotPiece.setText(rs.getString("TotalPieces"));               
                desti.setSelectedItem(rs.getString("Destination"));
                jDateChooser2.setDate(rs.getDate("ShipDate"));
                Vid.setText(rs.getString("DriverId"));
                lw.setText(rs.getString("Maxweight"));
                ds.setSelectedItem(rs.getString("DeliveryStatus"));
                
                ser.setText(null);
                lable3.setText(null);
            }
            else if(ser.getText().length()>0)
            {
                lable3.setText("Inavalid delivery Id");
                ser.setText(null);
            }
            else
            {
                lable3.setText("Please enter delivery id..");
                
            }
            
            
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
                  jPanel2.setBackground(new Color(0,0,0));

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
          
        
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String sql="select VehicleID from driverassignment11111 where DriverId=? ";
        Vid.setText(null);
        try{
            pst=con.prepareStatement(sql);
            pst.setString(1,jComboBox1.getSelectedItem().toString());
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                Vid.setText(rs.getString("VehicleID"));
                truevid=true;
               
            }
            else
            {
                Vid.setText("Not Assigned");
                truevid=false;
            }
            tableload();
        }
        catch(Exception e)
        {
        
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void lwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lwFocusLost
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        String a = HandlingDate=sd.format(jDateChooser1.getDate());
        if(!a.isEmpty())
        {
        for (int i=0;i<a.length();i++)
            {
        if(Character.isLetter(a.charAt(i)))
                {   
                       JOptionPane.showMessageDialog(null,"letters are not allowed to enter");
                       jDateChooser1.setDate(null);
                }
            }
        }
//            }// TODO add your handling code here:
    }//GEN-LAST:event_lwFocusLost

    private void TotPieceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TotPieceFocusLost
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        String a = HandlingDate=sd.format(jDateChooser1.getDate()); 
        
        if(!a.isEmpty())
        {
        for (int i=0;i<a.length();i++)
            {
        if(Character.isLetter(a.charAt(i)))
                {   
                       JOptionPane.showMessageDialog(null,"letters are not allowed to enter");
                       jDateChooser1.setDate(null);
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TotPieceFocusLost

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
    jPanel2.setBackground(new Color(102,102,102));        
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
         jPanel3.setBackground(new Color(0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
         jPanel3.setBackground(new Color(102,102,102));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
         jPanel4.setBackground(new Color(0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
         jPanel4.setBackground(new Color(102,102,102));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
         jPanel6.setBackground(new Color(102,102,102));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
         jPanel5.setBackground(new Color(0,0,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
         jPanel5.setBackground(new Color(102,102,102));
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
try {
                con=dbconnect.connect();
                String reportPath = "C:\\Users\\Tharindu sachintha\\Documents\\NetBeansProjects\\Security_Managment\\src\\ireport\\report2.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                JasperPrint jp = JasperFillManager.fillReport(jr,null,con);
                JasperViewer.viewReport(jp,false);
                
                
            
        } catch (Exception e) {
            System.out.println(e);
        }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotPiece;
    private javax.swing.JLabel Vid;
    private javax.swing.JTextField deID;
    private javax.swing.JComboBox desti;
    private javax.swing.JComboBox ds;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lable1;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel lable3;
    private javax.swing.JTextField lw;
    private javax.swing.JTextField oid;
    private javax.swing.JTextField ser;
    private javax.swing.JTextField styl;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
